### ISSUE TITLE
All tests are red

### ISSUE THREAD

**Issue by vadimzozulya** [smarchenko/SitecoreDI.NSubstitute.Helper#5]
All tests are red with error messages:

`Could not load file or assembly 'Lucene.Net, Version=3.0.3.0, Culture=neutral, PublicKeyToken=85089178b9ac3181' or one of its dependencies. The system cannot find the file specified.`
or
`Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
`

**Comment by smarchenko** [comment]
Right, I had all these assemblies locally :( Thanks!
